import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope, Open_Sans } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/react";
import { ThemeProvider } from "@/app/_components/miscellaneous/theme-provider";

const heading = Open_Sans({
  variable: "--heading",
  subsets: ["latin"],
});

const paragraph = Manrope({
  variable: "--paragraph",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${heading.variable} ${paragraph.variable} antialiased bg-background w-screen min-h-screen relative`}
      >
        <ThemeProvider defaultTheme="dark" attribute="class">
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
